In [1]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [2]:
# Load the minimum required library to run the functions
from SuperSonic import Simulator_noGPU
from numpy.random import uniform

In [3]:
dt = 0.01
DeltaT = 1
TotalT = 10
n_sim = 2

In [55]:
mu_x = uniform(1.5e4, 4e4, size=(n_sim,1))
mu_y = uniform(1e4, 140e4, size=(n_sim,1))
k_x = uniform(3e-3, 16e-3, size=(n_sim,1))
k_y = uniform(1.5e-2, 30e-2, size=(n_sim,1))
k_int = uniform(1e-3, 6e-3, size=(n_sim,1))
tau = uniform(2e-2, 20e-2, size=(n_sim,1))
eps = uniform(0.5, 6, size=(n_sim,1))
D_x = uniform(5.5, 15.5, size=(n_sim,1))
D_y = uniform(1, 530, size=(n_sim,1))
sigma = uniform(4, 260, size=(n_sim,1))

In [4]:
mu_x = uniform(1.5e4, 4e4, size=(n_sim,1))
mu_y = uniform(1e4, 140e4, size=(n_sim,1))
k_x = uniform(0.1, 0.5, size=(n_sim,1))
k_y = uniform(0.1, 0.5, size=(n_sim,1))
k_int = uniform(0.1, 0.5, size=(n_sim,1))
tau = uniform(0.1, 0.5, size=(n_sim,1))
eps = uniform(0.1, 0.5, size=(n_sim,1))
D_x = uniform(0.1, 0.5, size=(n_sim,1))
D_y = uniform(0.1, 0.5, size=(n_sim,1))
sigma = uniform(0.1, 0.5, size=(n_sim,1))

In [5]:
theta = [mu_x, mu_y, k_x, k_y, k_int, tau, eps, D_x, D_y]
# theta[-4][theta[-4] == 0]

In [6]:
x_trace, s = Simulator_noGPU(dt, DeltaT, TotalT, n_sim, theta)


In [7]:
from numpy import float32
print(float32(mu_y))
print(mu_y)
print(mu_x)
print(float32(mu_x))
x_trace

[[1311844.9 ]
 [ 425665.53]]
[[1311844.8843164 ]
 [ 425665.51882462]]
[[34315.47863154]
 [26810.47839195]]
[[34315.48 ]
 [26810.479]]


array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [8]:
from numpy import sqrt
from numpy.random import randn

In [16]:
mu_x*(- k_x * 0 + k_int*0)*dt                +          sqrt(2*mu_x*D_x*dt)     *randn(n_sim,1)

array([[-8.18974337],
       [11.51995791]])

In [17]:
mu_y*(-k_y*0 + k_int*0 + 0)*dt        +          sqrt(2*mu_y*D_y*dt)     *randn(n_sim,1)

array([[-66.89171741],
       [-46.09313599]])